# Generated by Django 5.0 on 2023-12-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='distrbution_expense',
            new_name='distribution_expense',
        ),
    ]
