# Generated by Django 5.0 on 2023-12-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_distrbution_expense_book_distribution_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(),
        ),
    ]
